### PR TITLE
add rinkeby

### PR DESCRIPTION
**Pull request by szerintedmi**
Added docker compose files for Rinkeby based on https://github.com/HydroProtocol/protocol/pull/6

For WETH  [0xc778417e063141139fce010982780140aa0cd5ab](https://rinkeby.etherscan.io/address/0xc778417e063141139fce010982780140aa0cd5ab) is used based on [this post](https://blog.0xproject.com/canonical-weth-a9aa7d0279dd)

### CODE REVIEW

**Comment by szerintedmi** [comment]
It seems to run :
```
cp docker-compose-rinkeby.yaml docker-compose.yaml
docker-compose pull && docker-compose up
```

The only thing I noticed that I receive a couple of errors in the log when I launch. But the same errors I got when I launch it with the existing ropsten configs.
```
hydro-box-dex-launcher | time="2019-05-13T06:53:15Z" level=info msg=___CHANGE_ME___
hydro-box-dex-launcher | panic: invalid length, need 256 bits
hydro-box-dex-launcher | 
hydro-box-dex-launcher | goroutine 1 [running]:
hydro-box-dex-launcher | github.com/HydroProtocol/hydro-sdk-backend/launcher.NewDefaultSignService(0xc00002402f, 0xf, 0xc0001e1f28, 0xf, 0xc000082360)
hydro-box-dex-launcher | 	/go/pkg/mod/github.com/!hydro!protocol/hydro-sdk-backend@v0.0.30/launcher/signer.go:64 +0x167
hydro-box-dex-launcher | main.run(0xc000072058)
hydro-box-dex-launcher | 	/app/cli/launcher/main.go:28 +0x1bb
hydro-box-dex-launcher | main.main()
hydro-box-dex-launcher | 	/app/cli/launcher/main.go:116 +0x22

...
hydro-box-dex-launcher exited with code 2
```

**Comment by davidqhr** [comment]
It seems you didn't set a useable relayer address before you launch the dex. The relayer address private key is still `___CHANGE_ME___`. Please read this [manual](https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/manual/change-network-and-run-from-source.md#step-2-prepare-a-relayer-address). In the step 2, you should prepare a relayer address and change the ENVS before the launch.

**Comment by szerintedmi** [comment]
> It seems you didn't set a useable relayer address before you launch the dex. The relayer address private key is still `___CHANGE_ME___`. Please read this [manual](https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/manual/change-network-and-run-from-source.md#step-2-prepare-a-relayer-address). In the step 2, you should prepare a relayer address and change the ENVS before the launch.

Of course... Thanks. I tried only on localhost before :)

Are you running any relayers by yourself on testnets? Could we add [our token](https://rinkeby.etherscan.io/address/0x79065a165ec09e6a89d584a14872802717fe12a3) to the test config on rinkeby in this PR?

**Comment by davidqhr** [comment]
We have a temporary dex running on `http://dex-demo.hydroprotocol.io` now. But I can't promise it will be running all the time. I think the scaffold-dex project should have a very small seeds file. I suggest you to add your token through the cli command instead of put it in seed.

**Comment by szerintedmi** [comment]
> We have a temporary dex running on `http://dex-demo.hydroprotocol.io` now. But I can't promise it will be running all the time. I think the scaffold-dex project should have a very small seeds file. I suggest you to add your token through the cli command instead of putting it in seed.


Just thought you could include EUR stable coin in your example as well as USD to demonstrate you are not solely US focused ;)

**Comment by davidqhr** [comment]
lol... Sounds not bad.I'm open to it.

**Comment by szerintedmi** [comment]
@davidqhr : 
- added rinkeby network detection to web ( 91296af )- i did basic testing locally. unsure how it will rollup to your web docker image.
- you have `gasPrice: 80000` hardcoded for wallet tx-s. That causing my Rinkeby tx-s pending if I don't overwrite the default in Metamask sign panel. Is there any reason you have gasPrice hardcoded there?  AFAIK if you just don't provide then web3/metamask will fill in a reasonable default 
- on UI somehow the ETH balances are not showing up & I can't enable DAI nor HOT from the wallet (the buttons are disbled, other tokens' enable works). I'm going to fire up on Ropsten and try there too.

**Comment by davidqhr** [comment]
I create a new branch called [Augmint-rinkeby](https://github.com/HydroProtocol/hydro-scaffold-dex/tree/Augmint-rinkeby)

Changes:
- seed-sqlite.sql files are deleted
- Default gasPrice and gasLimit are deleted
- Fix some tslint issue
- Fix some wrong envs in rinkeby seeds and compose files. I think this is the reason why your approval action failed.

I can't get test ether in rinkeby env. The faucet seems bronken. Please help test on rinkeby.

**Comment by szerintedmi** [comment]
@davidqhr :great, thanks I'm going to try it on that branch.
Rinkeby test faucet works for me (just tried with facebook post auth). I can send you Rinkeby ETH, let me know your address

**Comment by davidqhr** [comment]
@szerintedmi `0x1EdAd6DaD44367a6e0e342E76e9Df595049b8224` Thanks

**Comment by szerintedmi** [comment]
> 0x1EdAd6DaD44367a6e0e342E76e9Df595049b8224

[Done](https://rinkeby.etherscan.io/tx/0x00f32f5f3dd98b878c1eb216422ff4fea59eb6ec566227847a8b38ba1115f2a1)

**Comment by szerintedmi** [comment]
@davidqhr 
Enable works for HOT and DAI as well know, thanks.

But It seems the fill tx reverts. Relayer [tx 1](https://rinkeby.etherscan.io/tx/0xece44bec2834bb43f3b95b04cab9576ceb589b0f64157edd3d9d3089d46996d1) & [tx2](https://rinkeby.etherscan.io/tx/0x5c4e5a27133ace01899278d340bdace5cf9d26a5ed5182e7c0779861a26aee2b)

image

**Comment by davidqhr** [comment]
@szerintedmi I think it is the relayer allowance issue. Take a look at https://github.com/HydroProtocol/hydro-scaffold-dex/blob/master/manual/change-network-and-run-from-source.md#step-2-prepare-a-relayer-address. The 4th in Step2.

**Comment by davidqhr** [comment]
@szerintedmi I checked the debug trace of the txs. The relayer address seems empty. The revert message is `INVALID_SENDER`.

image

Did you set a proper relayer address?

**Comment by szerintedmi** [comment]
> Did you set a proper relayer address?

No, sorry (i messed up  the merge from the new `Augmint-rinkeby` branch :) ). Fixing it and will keep you posted with the result.

Also am I still need `hydro-dex-ctl market approve HOT-WETH`if I enabled all tokens on the UI for the relayer? 

Unrelated but:

```
$ docker-compose exec admin sh
/ # hydro-dex-ctl market approve HOT-WETH
{"message":"Internal Server Error"}

/ # hydro-dex-ctl status
{
  "data": {
    "api": "offline",
    "engine": "offline",
    "launcher": "offline",
    "watcher": "offline",
    "web": "online",
    "websocket": "offline"
  },
  "desc": "success",
  "status": 0
}
```

**Comment by davidqhr** [comment]
> > Did you set a proper relayer address?
> 
> No, sorry (i messed up the merge from the new `Augmint-rinkeby` branch :) ). Fixing it and will keep you posted with the result.
> 
> Also am I still need `hydro-dex-ctl market approve HOT-WETH`if I enabled all tokens on the UI for the relayer?
> 
> Unrelated but:
> 
> ```
> $ docker-compose exec admin sh
> / # hydro-dex-ctl market approve HOT-WETH
> {"message":"Internal Server Error"}
> 
> / # hydro-dex-ctl status
> {
>   "data": {
>     "api": "offline",
>     "engine": "offline",
>     "launcher": "offline",
>     "watcher": "offline",
>     "web": "online",
>     "websocket": "offline"
>   },
>   "desc": "success",
>   "status": 0
> }
> ```

You need to set a proper relayer address, and make sure the relayer address has allowance on AEUR tokens. The command line is only a way to set allowance, you don't have to follow it. Then try your trades, they should be working.

**Comment by davidqhr** [comment]
> > Did you set a proper relayer address?
> 
> No, sorry (i messed up the merge from the new `Augmint-rinkeby` branch :) ). Fixing it and will keep you posted with the result.
> 
> Also am I still need `hydro-dex-ctl market approve HOT-WETH`if I enabled all tokens on the UI for the relayer?
> 
> Unrelated but:
> 
> ```
> $ docker-compose exec admin sh
> / # hydro-dex-ctl market approve HOT-WETH
> {"message":"Internal Server Error"}
> 
> / # hydro-dex-ctl status
> {
>   "data": {
>     "api": "offline",
>     "engine": "offline",
>     "launcher": "offline",
>     "watcher": "offline",
>     "web": "online",
>     "websocket": "offline"
>   },
>   "desc": "success",
>   "status": 0
> }
> ```

You need to set a proper relayer address, and make sure the relayer address has allowance on AEUR tokens. The command line is only a way to set allowance, you don't have to follow it. Then try your trades, they should be working.

**Comment by szerintedmi** [comment]
[Works now](https://rinkeby.etherscan.io/tx/0xf882bd08095333f01c5919d46360c5fce9f9003ec7c5beabfc58f088f1aa9902) , thank you for the support @davidqhr  :)
image


Minor thing: I'm not sure what is the intention with the`maker_fee_rate` and the `taker_fee_rate` settings in the seeded markets. In seeded data the maker fee is 0.3% and taker fee is is 0.1% if i read it well.
 It usually the other way around to encourage makers. As I used a copy-pasted WETH-DAI market in the seeder it's wrong in WETH-AEUR too :) 
Would it make sense to swap the fees in all markets?

**Comment by davidqhr** [comment]
Haha, if a taker pays more gas, that is definite an unreasonable fee structure. It's a known issue. We will fix.

**Comment by szerintedmi** [comment]
> Haha, if a taker pays more gas, that is definite an unreasonable fee structure. It's a known issue. We will fix.

Also makers provide liquidity so they usually get better conditions than takers

**Pull request merged**
